export const ADMIN_LAYERS = [
  {
    id: 'idn-province',
    name: 'Indonesia – Provinces',
    group: 'Provinces',
    geojsonPath: 'geojson/indonesia-province.geojson',
    featureIdField: 'kode',
    featureNameField: 'nama',
    bbox: [94.5, -11.5, 141.5, 6.5],
    samples: [],
    aliases: {
      'jakarta': '31',
      'dki jakarta': '31',
      'dki': '31',
      'yogyakarta': '34',
      'diy': '34',
      'di yogyakarta': '34',
      'kepri': '21',
      'babel': '19',
      'bangka belitung': '19',
      'kepulauan bangka belitung': '19',
      'sulsel': '73',
      'sumut': '12',
      'sumbar': '13',
      'sumsel': '16',
      'kalbar': '61',
      'kalteng': '62',
      'kaltim': '64',
      'kalsel': '63',
      'kaltara': '65',
      'sulut': '71',
      'sulteng': '72',
      'sulbar': '76',
      'sultra': '74',
      'ntb': '52',
      'ntt': '53',
      'malut': '82',
      'pabar': '92',
    },
    level: 'province',
  },

  // Regency layers — one per province
  { id: 'idn-regency-11', name: 'Aceh',                      group: 'Regencies', geojsonPath: 'geojson/regency/11-aceh.geojson',                                  featureIdField: 'kode', featureNameField: 'nama', bbox: [94.9719, 1.9772, 98.2873, 6.0768],       samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-12', name: 'Sumatera Utara',             group: 'Regencies', geojsonPath: 'geojson/regency/12-sumatera-utara.geojson',                        featureIdField: 'kode', featureNameField: 'nama', bbox: [97.0576, -0.6388, 100.4345, 4.3025],     samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-13', name: 'Sumatera Barat',             group: 'Regencies', geojsonPath: 'geojson/regency/13-sumatera-barat.geojson',                        featureIdField: 'kode', featureNameField: 'nama', bbox: [98.5965, -3.573, 101.8929, 0.9066],       samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-14', name: 'Riau',                       group: 'Regencies', geojsonPath: 'geojson/regency/14-riau.geojson',                                  featureIdField: 'kode', featureNameField: 'nama', bbox: [100.0508, -1.1269, 103.8136, 2.9212],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-15', name: 'Jambi',                      group: 'Regencies', geojsonPath: 'geojson/regency/15-jambi.geojson',                                 featureIdField: 'kode', featureNameField: 'nama', bbox: [101.1317, -2.7685, 104.4988, -0.7315],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-16', name: 'Sumatera Selatan',           group: 'Regencies', geojsonPath: 'geojson/regency/16-sumatera-selatan.geojson',                      featureIdField: 'kode', featureNameField: 'nama', bbox: [102.0639, -4.9242, 106.2206, -1.6269],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-17', name: 'Bengkulu',                   group: 'Regencies', geojsonPath: 'geojson/regency/17-bengkulu.geojson',                              featureIdField: 'kode', featureNameField: 'nama', bbox: [101.0224, -5.5144, 103.7905, -2.2899],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-18', name: 'Lampung',                    group: 'Regencies', geojsonPath: 'geojson/regency/18-lampung.geojson',                               featureIdField: 'kode', featureNameField: 'nama', bbox: [103.5907, -6.1676, 106.2804, -3.7239],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-19', name: 'Kepulauan Bangka Belitung',  group: 'Regencies', geojsonPath: 'geojson/regency/19-kepulauan-bangka-belitung.geojson',             featureIdField: 'kode', featureNameField: 'nama', bbox: [105.1085, -3.8016, 108.8718, -1.4935],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-21', name: 'Kepulauan Riau',             group: 'Regencies', geojsonPath: 'geojson/regency/21-kepulauan-riau.geojson',                        featureIdField: 'kode', featureNameField: 'nama', bbox: [103.2311, -1.2752, 109.1671, 4.7958],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-31', name: 'DKI Jakarta',                group: 'Regencies', geojsonPath: 'geojson/regency/31-daerah-khusus-ibukota-jakarta.geojson',         featureIdField: 'kode', featureNameField: 'nama', bbox: [106.3906, -6.3725, 106.973, -5.2024],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-32', name: 'Jawa Barat',                 group: 'Regencies', geojsonPath: 'geojson/regency/32-jawa-barat.geojson',                            featureIdField: 'kode', featureNameField: 'nama', bbox: [106.3703, -7.8205, 108.8466, -5.8066],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-33', name: 'Jawa Tengah',                group: 'Regencies', geojsonPath: 'geojson/regency/33-jawa-tengah.geojson',                           featureIdField: 'kode', featureNameField: 'nama', bbox: [108.556, -8.2113, 111.6914, -5.7258],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-34', name: 'DI Yogyakarta',              group: 'Regencies', geojsonPath: 'geojson/regency/34-daerah-istimewa-yogyakarta.geojson',            featureIdField: 'kode', featureNameField: 'nama', bbox: [110.0035, -8.2056, 110.8388, -7.5412],   samples: [{ key: 'yogya_hdi', label: 'HDI', file: 'yogyakarta_hdi.csv', keyCol: 'kode', keyType: 'id', valueCol: 'hdi' }], aliases: {}, level: 'regency' },
  { id: 'idn-regency-35', name: 'Jawa Timur',                 group: 'Regencies', geojsonPath: 'geojson/regency/35-jawa-timur.geojson',                            featureIdField: 'kode', featureNameField: 'nama', bbox: [110.8953, -8.7802, 116.2695, -5.043],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-36', name: 'Banten',                     group: 'Regencies', geojsonPath: 'geojson/regency/36-banten.geojson',                                featureIdField: 'kode', featureNameField: 'nama', bbox: [105.1014, -7.0138, 106.7799, -5.8076],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-51', name: 'Bali',                       group: 'Regencies', geojsonPath: 'geojson/regency/51-bali.geojson',                                  featureIdField: 'kode', featureNameField: 'nama', bbox: [114.4318, -8.848, 115.7124, -8.0617],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-52', name: 'Nusa Tenggara Barat',        group: 'Regencies', geojsonPath: 'geojson/regency/52-nusa-tenggara-barat.geojson',                   featureIdField: 'kode', featureNameField: 'nama', bbox: [115.821, -9.1075, 119.3461, -8.0801],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-53', name: 'Nusa Tenggara Timur',        group: 'Regencies', geojsonPath: 'geojson/regency/53-nusa-tenggara-timur.geojson',                   featureIdField: 'kode', featureNameField: 'nama', bbox: [118.9279, -11.0076, 125.1931, -7.779],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-61', name: 'Kalimantan Barat',           group: 'Regencies', geojsonPath: 'geojson/regency/61-kalimantan-barat.geojson',                      featureIdField: 'kode', featureNameField: 'nama', bbox: [108.5995, -3.0679, 114.2055, 2.0815],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-62', name: 'Kalimantan Tengah',          group: 'Regencies', geojsonPath: 'geojson/regency/62-kalimantan-tengah.geojson',                     featureIdField: 'kode', featureNameField: 'nama', bbox: [110.7332, -3.5414, 115.8494, 0.7906],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-63', name: 'Kalimantan Selatan',         group: 'Regencies', geojsonPath: 'geojson/regency/63-kalimantan-selatan.geojson',                    featureIdField: 'kode', featureNameField: 'nama', bbox: [114.3471, -4.9427, 117.4581, -1.3149],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-64', name: 'Kalimantan Timur',           group: 'Regencies', geojsonPath: 'geojson/regency/64-kalimantan-timur.geojson',                      featureIdField: 'kode', featureNameField: 'nama', bbox: [113.8361, -2.4096, 119.0371, 2.5664],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-65', name: 'Kalimantan Utara',           group: 'Regencies', geojsonPath: 'geojson/regency/65-kalimantan-utara.geojson',                      featureIdField: 'kode', featureNameField: 'nama', bbox: [114.5616, 1.1141, 117.9882, 4.4085],     samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-71', name: 'Sulawesi Utara',             group: 'Regencies', geojsonPath: 'geojson/regency/71-sulawesi-utara.geojson',                        featureIdField: 'kode', featureNameField: 'nama', bbox: [123.105, 0.2923, 127.1635, 5.5659],       samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-72', name: 'Sulawesi Tengah',            group: 'Regencies', geojsonPath: 'geojson/regency/72-sulawesi-tengah.geojson',                       featureIdField: 'kode', featureNameField: 'nama', bbox: [119.4268, -3.6397, 124.1812, 1.3743],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-73', name: 'Sulawesi Selatan',           group: 'Regencies', geojsonPath: 'geojson/regency/73-sulawesi-selatan.geojson',                      featureIdField: 'kode', featureNameField: 'nama', bbox: [117.0383, -7.7589, 122.2226, -1.9477],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-74', name: 'Sulawesi Tenggara',          group: 'Regencies', geojsonPath: 'geojson/regency/74-sulawesi-tenggara.geojson',                     featureIdField: 'kode', featureNameField: 'nama', bbox: [120.8645, -6.2127, 124.6154, -2.7733],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-75', name: 'Gorontalo',                  group: 'Regencies', geojsonPath: 'geojson/regency/75-gorontalo.geojson',                             featureIdField: 'kode', featureNameField: 'nama', bbox: [121.1617, 0.3063, 123.5523, 1.0556],      samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-76', name: 'Sulawesi Barat',             group: 'Regencies', geojsonPath: 'geojson/regency/76-sulawesi-barat.geojson',                        featureIdField: 'kode', featureNameField: 'nama', bbox: [117.0588, -3.5706, 119.8749, -0.8495],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-81', name: 'Maluku',                     group: 'Regencies', geojsonPath: 'geojson/regency/81-maluku.geojson',                                featureIdField: 'kode', featureNameField: 'nama', bbox: [125.7225, -8.3439, 134.9084, -2.7262],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-82', name: 'Maluku Utara',               group: 'Regencies', geojsonPath: 'geojson/regency/82-maluku-utara.geojson',                          featureIdField: 'kode', featureNameField: 'nama', bbox: [124.2832, -2.4771, 129.9233, 2.6452],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-91', name: 'Papua',                      group: 'Regencies', geojsonPath: 'geojson/regency/91-papua.geojson',                                 featureIdField: 'kode', featureNameField: 'nama', bbox: [134.2997, -4.1162, 141.0027, 0.9379],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-92', name: 'Papua Barat',                group: 'Regencies', geojsonPath: 'geojson/regency/92-papua-barat.geojson',                           featureIdField: 'kode', featureNameField: 'nama', bbox: [131.5774, -4.3308, 135.2028, -0.7139],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-93', name: 'Papua Selatan',              group: 'Regencies', geojsonPath: 'geojson/regency/93-papua-selatan.geojson',                         featureIdField: 'kode', featureNameField: 'nama', bbox: [137.6408, -9.1255, 141.02, -4.5646],     samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-94', name: 'Papua Tengah',               group: 'Regencies', geojsonPath: 'geojson/regency/94-papua-tengah.geojson',                          featureIdField: 'kode', featureNameField: 'nama', bbox: [134.5853, -5.2177, 138.3539, -2.2746],   samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-95', name: 'Papua Pegunungan',           group: 'Regencies', geojsonPath: 'geojson/regency/95-papua-pegunungan.geojson',                      featureIdField: 'kode', featureNameField: 'nama', bbox: [137.7103, -5.3444, 141.0012, -3.107],    samples: [], aliases: {}, level: 'regency' },
  { id: 'idn-regency-96', name: 'Papua Barat Daya',           group: 'Regencies', geojsonPath: 'geojson/regency/96-papua-barat-daya.geojson',                      featureIdField: 'kode', featureNameField: 'nama', bbox: [129.3004, -2.2837, 133.4932, 1.0805],   samples: [], aliases: {}, level: 'regency' },
]

export const DEFAULT_LAYER_ID = 'idn-province'

export function getLayer(id) {
  return ADMIN_LAYERS.find((l) => l.id === id) ?? ADMIN_LAYERS[0]
}
